Libreria/urls.py
from django.conf.urls import url

from Gestion_Libreros.views import *


urlpatterns = [
    url(r'^$', Inicio.as_view(), name="Inicio"),
    url(r'^gestion_libros/$', GestionLibros.as_view(), name="GestionLibros"),
    url(r'^gestion_libros/nuevo_libro/$', NuevoLibro.as_view(), name="NuevoLibro"),
    url(r'^ajax/crear_autor/$', crear_autor, name="CrearAutor"),
    url(r'^ajax/crear_tag/$', crear_tag, name="CrearTag"),
    url(r'^ajax/crear_coleccion/$', crear_coleccion, name="CrearColeccion"),
    url(r'^ajax/crear_edicion/$', crear_edicion, name="CrearEdicion"),
    url(r'^ajax/crear_editorial/$', crear_editorial, name="CrearEditorial"),
    url(r'^ajax/eliminar_editorial/$', eliminar_editorial, name="EliminarEditorial"),
    url(r'^ajax/editar_editorial/$', editar_editorial, name="EditarEditorial"),
    url(r'^ajax/nuevo_sello/$', nuevo_sello, name="NuevoSello"),
    url(r'^gestion_libros/libro/(?P<pk>[0-9]+)$', LibroDetalles.as_view(), name="DetalleLibro"),
    url(r'^gestion_libros/editoriales/$', GestionEditoriales.as_view(), name="GestionEditoriales"),
]

Gestion_Libreros/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.core.exceptions import ValidationError
from django.db import models
from django.utils.translation import ugettext_lazy as _


default_error_messages = {
    'invalid_choice': _('El valor %r no es una opcion valida'),
    'null': _(u'Este campo es obligatorio.'),
    'blank': _(u'Este campo no puede estar en blanco.'),
    'max_length': _(u'La cantidad de caracteres debe ser de %(limit_value)s.'),
    'unique': _(u'E')
}


# def validar_isbn(value):
  #  if value.match('[0-9]'):
   #     raise ValidationError(
    #        _('%(value)s no es un numero'),
     #       params={'value': value},)


class Tag(models.Model):
    nombre = models.CharField(max_length=25, unique=True, error_messages={'unique': 'El nombre del tag no puede repetirse'}.update(default_error_messages))

    def __unicode__(self):
        return self.nombre


class Pais(models.Model):
    nombre = models.CharField(max_length=30, unique=True)

    def __unicode__(self):
        return self.nombre


class Autor(models.Model):
    nombre = models.CharField(max_length=35, error_messages=default_error_messages, unique=True)
    fecha_nac = models.DateField(verbose_name="fecha de nacimiento", error_messages=default_error_messages)
    pais = models.ForeignKey(Pais, on_delete=models.CASCADE, error_messages=default_error_messages)

    def __unicode__(self):
        return self.nombre


class Editorial(models.Model):
    nombre = models.CharField(max_length=45, unique=True, error_messages=dict(default_error_messages, **{'unique': 'Ya existe una editorial con el mismo nombre'}))

    def __unicode__(self):
        return self.nombre


class Sello(models.Model):
    nombre = models.CharField(max_length=25, unique=True)
    editorial = models.ForeignKey(Editorial, on_delete=models.CASCADE)

    def __unicode__(self):
        return self.nombre

    
class Librero(models.Model):
    nombre = models.CharField(max_length=30, unique=True)

    def __unicode__(self):
        return self.nombre


class Coleccion(models.Model):
    nombre = models.CharField(max_length=30, unique=True)

    def __unicode__(self):
        return self.nombre


class Libro(models.Model):
    titulo = models.CharField(max_length=40, error_messages=default_error_messages)
    subtitulo = models.CharField(max_length=40, null=True, error_messages=default_error_messages)
    resenna = models.TextField(max_length=600, verbose_name="reseña", error_messages=default_error_messages)
    autor = models.ForeignKey(Autor, on_delete=models.CASCADE, error_messages=default_error_messages)
    tags = models.ManyToManyField(Tag)
    coleccion = models.ForeignKey(Coleccion, on_delete=models.CASCADE, error_messages=default_error_messages)

    def __unicode__(self):
        return self.titulo


class Edicion(models.Model):
    # Tapas
    BLANDA = 1
    DURA = 2
    TAPAS = (
        (BLANDA, "Tapa blanda"),
        (DURA, "Tapa dura"),
    )

    # Encuadernado
    RUSTICA = 1
    ENCARTONADA = 2
    CARTONE = 3
    SUELTA = 4
    ENCUADERNADO = (
        (RUSTICA, "Encuadernado rustico"),
        (ENCARTONADA, "Encuadernado encartonado"),
        (CARTONE, "Encuadernado cartoné"),
        (SUELTA, "Encuadernado de tapa suelta")
    )
    # Tipo de isbn
    ISBN_10 = 1
    ISBN_13 = 2
    ISBN = {
        (ISBN_10, "ISBN"),
        (ISBN_13, "ISBN 13")
    }
    tipo_isbn = models.SmallIntegerField(choices=ISBN, error_messages=default_error_messages)
    isbn = models.CharField(max_length=13, unique=True, error_messages=default_error_messages)
    n_paginas = models.PositiveIntegerField(verbose_name="N° Paginas", error_messages=default_error_messages)
    idioma = models.CharField(max_length=20, error_messages=default_error_messages)
    cantidad = models.PositiveIntegerField(error_messages=default_error_messages)
    imagen = models.ImageField(upload_to='imagenes_edicion', error_messages=default_error_messages)
    anno = models.DateField(verbose_name="fecha de publicacion", error_messages=default_error_messages)
    tapa = models.SmallIntegerField(choices=TAPAS, error_messages=default_error_messages)
    encuadernado = models.SmallIntegerField(choices=ENCUADERNADO, error_messages=default_error_messages)
    libro = models.OneToOneField(Libro, on_delete=models.CASCADE, error_messages=default_error_messages)
    sello = models.ForeignKey(Sello, on_delete=models.CASCADE, error_messages=default_error_messages)

    def __unicode__(self):
        return self.sello.nombre


class Articulo(models.Model):
    BUENO = 1
    MAL = 2
    MUY_MAL = 3
    ESTADOS = (
        (BUENO, "Buen estado"),
        (MAL, "Mal estado"),
        (MUY_MAL, "Muy mal estado"),
    )
    estado = models.SmallIntegerField(choices=ESTADOS)
    edicion = models.ForeignKey(Edicion, on_delete=models.CASCADE)
    librero = models.ForeignKey(Librero, on_delete=models.CASCADE)

    def __unicode__(self):
        return self.estado

Gestion_Libreros/forms.py
from django.forms import ModelForm
from Gestion_Libreros.models import Edicion, Sello, default_error_messages, Editorial


class EdicionForm(ModelForm):
    class Meta:
        model = Edicion
        error_messages = default_error_messages
        fields = ['tipo_isbn', 'isbn', 'n_paginas', 'anno', 'idioma', 'tapa', 'encuadernado', 'sello', 'imagen']


class SelloForm(ModelForm):
    class Meta:
        model = Sello
        fields = ['nombre', 'editorial']

Gestion_Libreros/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.core.exceptions import ValidationError
from django.db import IntegrityError
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView, CreateView, DetailView
from forms import EdicionForm, SelloForm
from models import Libro, Pais, Autor, Tag, Coleccion, Editorial, Edicion


class Inicio(TemplateView):
    template_name = "Gestion_Libreros/index.html"

    def get_context_data(self, **kwargs):
        context = super(Inicio, self).get_context_data(**kwargs)
        context["titulo"] = "Inicio"
        context["ultimos_libros"] = Libro.objects.all()[:5]
        return context


class GestionEditoriales(TemplateView):
    template_name = "Gestion_Libreros/editoriales.html"

    def get_context_data(self, **kwargs):
        context = super(GestionEditoriales, self).get_context_data(**kwargs)
        context["titulo"] = "Editoriales"
        context["editoriales"] = list(reversed(Editorial.objects.all()[:15]))
        return context


class GestionLibros(TemplateView):
    template_name = "Gestion_Libreros/gestion_libros.html"

    def get_context_data(self, **kwargs):
        context = super(GestionLibros, self).get_context_data(**kwargs)
        context["titulo"] = "Gestion de libros"
        context["libros"] = Libro.objects.all()[:15]
        return context


class NuevoLibro(CreateView):
    success_url = 'http://127.0.0.1:8000/gestion_libros/'
    template_name = "Gestion_Libreros/nuevo_libro.html"
    model = Libro
    fields = ["titulo", "subtitulo", "resenna", "autor", "tags", "coleccion"]

    def get_context_data(self, **kwargs):
        context = super(NuevoLibro, self).get_context_data(**kwargs)
        context["titulo"] = "Nuevo Libro"
        context["paises"] = Pais.objects.all()
        return context


class LibroDetalles(DetailView):
    model = Libro
    template_name = "Gestion_Libreros/libro.html"

    def get_context_data(self, **kwargs):
        context = super(LibroDetalles, self).get_context_data(**kwargs)
        context["titulo"] = self.object.titulo
        context["formEdicion"] = EdicionForm
        context["formSello"] = SelloForm
        return context


def crear(modelo, data={}):
    try:
        modelo.full_clean()
        modelo.save()
        data["nombre"] = modelo.nombre
        data["id"] = modelo.id
        data["error"] = False
        return JsonResponse(data)
    except ValidationError as e:
        data["error"] = True
        data.update(e.message_dict)
        return JsonResponse(data)
    except IntegrityError as i:
        data["error"] = True
        data.update(i.message_dict)
        return JsonResponse(data)


# Ajax views

def crear_edicion(request):
    edicion_form = EdicionForm(request.POST)
    data = {}
    if edicion_form.is_valid():
        e = edicion_form.save()
        data["edicion"] = e
    else:
        data["error"] = True
        data.update(edicion_form.errors)
    return JsonResponse(data)


def crear_editorial(request):
    nombre = request.GET.get('nombre', None)
    data = {}
    if nombre == "":
        data["error"] = True
        data["nombre"] = "Debe ingresar un nombre para la editorial."
        return JsonResponse(data)
    return crear(Editorial(nombre=nombre))


def crear_autor(request):
    nombre = request.GET.get('nombre', None)
    fecha_nac = request.GET.get('fecha_nac', None)
    pais = request.GET.get('pais', None)
    data = {}
    if nombre == "":
        data["nombre"] = "Debe ingresar un nombre."
    if fecha_nac == "":
        data["fecha_nac"] = "Debe ingresar una fecha."
    if pais == "":
        data["pais"] = "Debe seleccionar un pais."
    if data:
        data["error"] = True
        return JsonResponse(data)
    return crear(Autor(nombre=nombre, fecha_nac=fecha_nac, pais=Pais.objects.get(pk=pais)))


def crear_tag(request):
    nombre = request.GET.get('nombre', None)
    data = {}
    if nombre == "":
        data["error"] = True
        data["nombre"] = "Debe ingresar un nombre para el tag."
        return JsonResponse(data)

    return crear(Tag(nombre=nombre))


def crear_coleccion(request):
    nombre = request.GET.get('nombre', None)
    data = {}
    if nombre == "":
        data["error"] = True
        data["nombre"] = "Debe ingresar un nombre para la coleccion"
        return JsonResponse(data)
    return crear(Coleccion(nombre=nombre))


def nuevo_sello(request):
    sello_form = SelloForm(request.POST)
    data = {}
    if sello_form.is_valid():
        s = sello_form.save()
        data["nombre"] = s.nombre
        data["id"] = s.id
    else:
        data["error"] = True
        data.update(sello_form.errors)
    return JsonResponse(data)


@csrf_exempt
def eliminar_editorial(request):
    e = Editorial.objects.get(pk=request.GET.get('pk')).delete()
    return JsonResponse({"response": e})


def editar_editorial(request):
    e = Editorial.objects.get(pk=request.GET.get('pk'))
    e.nombre = request.GET.get('nombre')
    return crear(e)

Gestion_Libreros/templates/Gestion_Libreros/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <meta charset="UTF-8">
    <title>{{ titulo }}</title>
    <link rel="stylesheet" href="{% static 'css/materialize.min.css' %}" >
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <script type="text/javascript" src="{% static 'js/lib/jquery.js' %}"></script>
    <script src="{% static 'js/lib/materialize.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    {% block script %}
    {% endblock %}

</head>
<body>
    <ul id="slide-out" class="side-nav fixed hide-on-med-and-down">
        <li>
            <div class="row center">
                <div class="col m12 s12 " >
                    <div class="row">
                        <div class="input-field col s6 s12">
                            <i class="material-icons prefix">search</i>
                            <input type="text" placeholder="Buscar"  class="autocomplete" >
                        </div>
                    </div>
                </div>
            </div>
        </li>
        <li>
            <ul class="collapsible" data-collapsible="accordion">
                <li>
                    <div class="collapsible-header" data-href="{% url 'GestionLibros' %}">
                        Gestion de Libros
                    </div>
                    <div class="collapsible-body">
                        <ul>
                            <li><a  href="">Autores</a></li>
                            <li><a href="{% url 'GestionEditoriales' %}">Editoriales</a></li>
                            <li><a href="#">Tags</a></li>
                            <li><a href="#">Colecciones</a></li>
                        </ul>
                    </div>
                </li>
                <li>
                    <div class="collapsible-header">
                      Second
                    </div>
                    <div class="collapsible-body">
                        asdadsasdasd
                    </div>
                </li>
            </ul>
        </li>
    </ul>
    <nav class="wrapper">
        <div class="nav-wrapper brown">
            <a href="{% url 'Inicio' %}" class="brand-logo">Libreria</a>
            <a href="#" data-activates="mobile" class="button-collapse"><i class="material-icons">menu</i></a>
            <ul class="right hide-on-med-and-down">
                <li><a href="{% url 'GestionLibros' %}">Gestion de Libros</a></li>
                <li><a href="#">Gestion de Libreros</a></li>
            </ul>
        </div>
    </nav>
    <div class="content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

Gestion_Libreros/templates/Gestion_Libreros/editoriales.html
{% extends 'Gestion_Libreros/base.html' %}
{% load static %}

{% block script %}
    <script src="{% static 'js/editoriales.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="">
        <h2>Editoriales</h2>
    </div>
    <div class="row">
        <div class="input-field col s8">
            <i class="material-icons prefix">search</i>
            <input id="busqueda" type="text" placeholder="Buscar"  class="autocomplete" >
        </div>
        <div class="col s3 m3">
            <a class="btn modal-trigger" href="#modal-editorial">Nueva editorial</a>
        </div>
    </div>
    <div class="row">
        <table id="tabla-editorial" class="bordered  highlight">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th colspan="2">Accion</th>
                </tr>
            </thead>
            <tbody>
                {% for editorial in editoriales %}
                    <tr id="{{ editorial.id }}">
                      <td>{{editorial.nombre}}</td>
                      <td>
                          <a class="modal-trigger" onclick="copiarAModal({{ editorial.id }})" href="#modal-editar-editorial">
                              <i class="material-icons" >edit</i> Editar
                          </a>
                      </td>
                      <td>
                          <a style="cursor: pointer;" data-id="{{ editorial.id }}" id="eliminar_editorial">
                              <i class="material-icons">close</i> Eliminar
                          </a>
                      </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <!-- Crear Editorial modal  -->
    <div id="modal-editorial" class="modal">
        <div class="modal-content">
            <h4>Nueva Editorial</h4>
            <form id="nuevo-editorial" method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="input-field col s6 offset-s3">
                        <input name="nombre" placeholder=""  id="nombre-editorial" type="text">
                        <label>Nombre: </label>
                    </div>
                </div>
            </form>
        </div>
        <div class="modal-footer">
            <button type="button" id="crear_editorial" class="btn-flat">Guardar</button>
        </div>
    </div>
    <!--Fin crear editorial -->
    <!--Editar editorial modal-->
    <div id="modal-editar-editorial" class="modal">
        <div class="modal-content">
            <h4>Editando Editorial</h4>
            <form id="editar-editorial" method="post">
                {% csrf_token %}
                <div class="row">
                    <input type="hidden" name="pk" id="editorial-id">
                    <div class="input-field col s6 offset-s3">
                        <input name="nombre" placeholder="" id="nombre-editar-editorial" type="text">
                        <label>Nombre: </label>
                    </div>
                </div>
            </form>
        </div>
        <div class="modal-footer">
            <button type="button" id="editar_editorial" class="btn-flat">Guardar</button>
        </div>
    </div>
{% endblock %}

Gestion_Libreros/templates/Gestion_Libreros/gestion_libros.html
{% extends 'Gestion_Libreros/base.html' %}
{% block content %}
    <div class="">
        <h2>Libros</h2>
    </div>
    <div class="row">
        <div class="input-field col s3">
            <i class="material-icons prefix">search</i>
            <input id="busqueda" type="text" placeholder="Buscar"  class="autocomplete" >
        </div>
        <div class="input-field  col m3 s3">
            <select class="">
                <option value="" disabled selected>Escoge una opcion</option>
                <option value="1">Titulo</option>
                <option value="2">Fecha de publicacion</option>
                <option value="3"></option>
            </select>
            <label>Ordenar por:</label>
        </div>
        <div class="col s3 m3">
            <a href="{% url 'NuevoLibro' %}" class="btn">Nuevo Libro</a>
        </div>
    </div>
    {% for libro in libros %}
        <div class="row">
            <div class="col s12 m12">
                <div class="card horizontal hoverable">
                    <div class="card-image">
                      <img style="max-height: 80px;" src="https://lorempixel.com/100/190/nature/6">
                    </div>
                    <div class="card-stacked" >
                        <a href="{% url 'DetalleLibro' libro.id %}">
                            <span style="display:block" class="card-content">
                                <span>{{libro.titulo}}</span>
                            </span>
                        </a>
                    </div>
                    <div class="card-stacked">
                        <div  class="card-content">
                            <p>{{libro.autor.nombre}}</p>
                        </div>
                    </div>
                    <div class="card-stacked">
                        <div class="card-content">
                            <a class='dropdown-button btn blue' href='#' data-activates='{{ libro.id }}'>Ediciones</a>
                            <ul id="{{ libro.id }}" class="dropdown-content">

                                <li><a href="#!">Tapa blanda</a></li>
                                <li><a href="#!">Tapa dura</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="card-stacked">
                        <div class="card-content">
                            <p>Stock: </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock content %}

Gestion_Libreros/templates/Gestion_Libreros/index.html
{% extends 'Gestion_Libreros/base.html' %}
{% block content %}
    <div class="">
        <div class="row">
            <h5>Libros Añadidos recientemente</h5>
        </div>
        <div class="row">
            <div class="col s12 m12">
                <h6 class="header">Harry potter</h6>
                <div class="card horizontal">
                    <div class="card-image">
                        <img style="max-height: 260px" src="https://imagessl2.casadellibro.com/a/l/t0/62/9788498382662.jpg">
                    </div>
                    <div class="card-stacked">
                        <div class="card-content">
                            <p>
                               Harry Potter se ha quedado huérfano y vive en casa de sus abominables tíos y del insoportable primo Dudley. Harry se siente muy triste y solo, hasta que un buen día recibe una carta que cambiará su vida para siempre. En ella le comunican que ha sido aceptado como alumno en el colegio interno Hogwarts de magia y hechicería...
                            </p>
                            <p>
                                Autora: J. K. Rowling<br>
                                Editorial: Salamandra, letras de bolsillo.<br>
                                Edición: Marzo del 2012, Barcelona, España.
                                254 páginas
                                Tapa blanda.
                            </p>
                        </div>
                        <div class="card-action">
                            <a href="#">Ver</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

Gestion_Libreros/templates/Gestion_Libreros/libro.html
{% extends 'Gestion_Libreros/base.html' %}
{% load static %}
{% block script %}
    <script src="{% static 'js/libro.js' %}"></script>
{% endblock %}

{% block content %}
    <article class="row">
        <section class="col s3">
            <img style="max-width: 100%" src="https://imagessl2.casadellibro.com/a/l/t0/62/9788498382662.jpg">
        </section>
        <section class="col s9">
            <div class="row">
                <span class="titulo">{{ object.titulo }}</span>
                {% if object.subtitulo %}
                    <span class="subtitulo">{{ object.subtitulo }}</span>
                {% endif %}
                <div>
                    de <a href="#">{{ object.autor.nombre }} (Autor)</a>
                </div>
                <div>
                    <span class="bold">Tags: </span>
                    {% for tag in object.tags.all %}
                        <a href="#">#{{ tag.nombre }}</a>
                    {% endfor %}
                </div>
                <div>
                    <span class="bold">Pertenece a la coleccion: </span><a href="#">{{ libro.coleccion.nombre }}</a>
                </div>
            </div>
            <div class="row">
                <div class="divider"></div>
            </div>
            <div class="row">
                <span class="titulo">Ediciones: </span>
                <div class="edicion bold" id="">
                    <span>
                        Tapa dura
                    </span>
                </div>
                <div class="edicion">
                    <span>
                        Tapa blanda
                    </span>
                </div>
                <a class="btn btn-floating modal-trigger" href="#modal-edicion"><i class="material-icons">add</i></a>
            </div>
        </section>
    </article>
    <!-- Edicion modal -->
    <div id="modal-edicion" class="modal">
        <div class="modal-content">
            <h4>Nueva Edicion</h4>
            <form id="nuevo-edicion"  method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in formEdicion %}
                    <div class="row">
                        {% if field.name == "imagen" %}
                            <div class="file-field input-field col s8 offset-s2">
                                <div class="btn">
                                    <span>Imagen</span>
                                    <input type="file"  accept="image/jpeg" name="imagen" required id="id_imagen">
                                </div>
                                <div class="file-path-wrapper" id="path-id_imagen">
                                    <input class="file-path validate" type="text">
                                </div>
                            </div>
                        {% elif field.name == "anno" %}
                            <div class="input-field col s8 offset-s2">
                                <input type="text" class="datepicker" name="anno" id="id_anno" >
                                <label for="id_anno">Fecha de publicacion </label>
                            </div>
                        {% else %}
                            <div class="input-field col s8 offset-s2">
                                {{ field.errors }}
                                {{ field }} {{ field.label_tag }}
                            </div>
                        {% endif %}
                        {% if field.name == "sello" %}
                            <div class="col s1 ">
                                <a class="btn btn-floating modal-trigger" href="#modal-{{ field.name }}"><i class="material-icons">add</i></a>
                            </div>
                        {% endif %}
                    </div>
                {% endfor %}
            </form>
        </div>
        <div class="modal-footer">
            <button type="button" id="crear_edicion" class="modal-action btn-flat">Guardar</button>
        </div>
    </div>
    <!-- end edicon modal -->
    <!-- Sello-modal -->
    <div id="modal-sello" class="modal">
        <div class="modal-content">
            <h4>Nuevo sello</h4>
            <form id="nuevo-sello" method="post">
                {% csrf_token %}
                {% for field in formSello %}
                    <div class="row">
                        <div class="input-field col s8 offset-s2">
                            {{ field.errors }}
                            {{ field }} {{ field.label_tag }}
                        </div>
                    </div>
                {% endfor %}
            </form>
        </div>
        <div class="modal-footer">
            <button type="button" id="crear_sello" class="modal-action btn-flat">Guardar</button>
        </div>
    </div>
    <!-- end Sellomodal -->
{% endblock %}

Gestion_Libreros/templates/Gestion_Libreros/nuevo_libro.html
{% extends 'Gestion_Libreros/base.html' %}

{% load static %}
{% block script %}
    <script src="{% static 'js/nuevo_libro.js' %}"></script>
{% endblock %}

{% block content %}
    <form  method="post">{% csrf_token %}
        <div>
            {% for field in form %}
                <div class="row">
                    <div class="input-field col s8 offset-s2">
                        {{ field.errors }}
                        {{ field }} {{ field.label_tag }}
                    </div>
                    {% if field.name == "autor" or field.name == "tags" or field.name == "coleccion" %}
                        <div class="col s1 ">
                            <a class="btn btn-floating modal-trigger" href="#modal-{{ field.name }}"><i class="material-icons">add</i></a>
                        </div>
                    {% endif %}
                </div>
            {% endfor %}
            <div class="row">
                <input type="submit" class="btn col s2 offset-s8" value="Guardar" >
            </div>
        </div>
    </form>
    <!--- Autor Modal  -->
    <div id="modal-autor" class="modal">
        <div class="modal-content">
            <h4>Nuevo Autor</h4>
            <form id="nuevo-autor" method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="input-field col s6 offset-s3">
                        <input name="nombre" id="id_nombre" type="text">
                        <label>Nombre: </label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s6 offset-s3">
                        <input type="text" class="datepicker" name="fecha_nac" id="id_fecha_nac" >
                        <label>Fecha de nacimiento: </label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s6 offset-s3">
                        <select  name="pais" id="id_pais">
                            <option value="">-----</option>
                            {% for pais in paises %}
                                <option value="{{ pais.id }}">{{ pais.nombre }}</option>
                            {% endfor %}
                        </select>
                        <label>Seleccionar pais: </label>
                    </div>
                </div>
            </form>
        </div>
        <div class="modal-footer">
            <button type="button" id="crear_autor" class="modal-action btn-flat">Guardar</button>
        </div>
    </div>
    <!--- end Autor Modal  -->

    <!--- Tag modal -->
    <div id="modal-tags" class="modal">
        <div class="modal-content">
            <h4>Nuevo Tag</h4>
            <form id="nuevo-tag" method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="input-field col s6 offset-s3">
                        <input name="nombre" id="nombre-tag" type="text">
                        <label>Nombre: </label>
                    </div>
                </div>
            </form>
        </div>
        <div class="modal-footer">
            <button type="button" id="crear_tag" class="modal-action btn-flat">Guardar</button>
        </div>
    </div>
    <!--- end tag modal -->

    <!--- Coleccion modal -->
    <div id="modal-coleccion" class="modal">
        <div class="modal-content">
            <h4>Nueva Coleccion</h4>
            <form id="nuevo-coleccion" method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="input-field col s6 offset-s3">
                        <input name="nombre" id="nombre-coleccion" type="text">
                        <label>Nombre: </label>
                    </div>
                </div>
            </form>
        </div>
        <div class="modal-footer">
            <button type="button" id="crear_coleccion" class="modal-action btn-flat">Guardar</button>
        </div>
    </div>
    <!--- end coleccion modal -->
{% endblock content %}